### PR TITLE
adding all BackBone Labs liquid staking tokens to registry

### PR DESCRIPTION
**Pull request by tvl83**
- bHUAHUA
- bJUNO
- bLUNA

### CODE REVIEW

**Comment by HeesungB** [comment]
@tvl83 Hello. Could you check your token metadata?
and You should set file format as png or svg.

```
Fetched metadata: { name: 'bHUAHUA Token', symbol: 'bHUAHUA', decimals: 6 }
Fetched metadata is not same with the token metadata: (expected: {"name":"bHUAHUA Token","symbol":"bHUAHUA","decimals":6}, actual: {"name":"boneHUAHUA","symbol":"bHUAHUA","decimals":6}), contract: chihuahua1jz5n4aynhpxx7clf2m8hrv[9](https://github.com/chainapsis/keplr-contract-registry/actions/runs/8363649335/job/22958482328?pr=30#step:7:10)dp5nz83k67fgaxhy4p9dfwl6zssrq3ymr6w, chain: chihuahua)
```

**Comment by tvl83** [comment]
Yes i will update the PR with the correct image format and the metadata.

**Comment by HeesungB** [comment]
@tvl83 Could you check your token metadata?

```
Fetched metadata: { name: 'bJuno Token', symbol: 'bJuno', decimals: 6 }
Fetched metadata is not same with the token metadata: (expected: {"name":"bJuno Token","symbol":"bJuno","decimals":6}, actual: {"name":"bJuno Token","symbol":"bJUNO","decimals":6}), contract: juno1mvkgcr5uce2rnpzr4qrzf50hx4qreuwzlt7fzsjrhjud3xnjmttq5mkh2m, chain: juno)
```

**Comment by tvl83** [comment]
Yes I will fix this soon and I will check all the other tokens onchain data.

**Comment by HeesungB** [comment]
@tvl83 Hello.
You can also use the command below to check the validation locally.
```
 yarn validate:token cosmos/phoenix/tokens/terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml.json

```

```
Fetched metadata is not same with the token metadata: (
expected: {"name":"boneLuna","symbol":"bLUNA","decimals":6}, 
actual: {"name":"boneLUNA","symbol":"bLUNA","decimals":6}), 
contract: terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml, chain: phoenix)
```

**Pull request merged**
