### PR TITLE
feat: add ASTRO and xASTRO cw20 on Terra

### PR DESCRIPTION
**Pull request by afsardo**

### CODE REVIEW

**Comment by HeesungB** [comment]
@afsardo Hi, is it possible to rebase the main branch?

**Comment by afsardo** [comment]
@HeesungB think it is

**Comment by HeesungB** [comment]
@afsardo Rebase please!

**Comment by afsardo** [comment]
I think it is?

Screenshot 2024-02-27 at 15 33 43

**Comment by HeesungB** [comment]
@afsardo Thank you for contribution!

**Pull request merged**
