### PR TITLE
Add Tritium on terraclassic

### PR DESCRIPTION
**Pull request by andrexbass**

### CODE REVIEW

**Comment by vegasmorph** [comment]
?

**Comment by HeesungB** [comment]
@andrexbass @vegasmorph Please also add the basefile for `terra classic` to your pr here.

**Comment by HeesungB** [comment]
@andrexbass @vegasmorph Could you add base.json file also?

**Comment by vegasmorph** [comment]
> @andrexbass @vegasmorph Could you add base.json file also?

https://github.com/chainapsis/keplr-contract-registry/pull/28

**Comment by HeesungB** [comment]
@vegasmorph You should have chain information like the file below.
https://github.com/chainapsis/keplr-contract-registry/pull/11/files

**Comment by andrexbass** [comment]
Our chain base file already exists and is exactly this:
https://github.com/chainapsis/keplr-contract-registry/blob/main/cosmos/columbus/base.json

"columbus-5" is the Terra Classic chain

**Comment by HeesungB** [comment]
@andrexbass @vegasmorph Sorry my bad.
Could you resize image?
```
Reduce image size to 512x512 or smaller (expected: 512x512, actual: 631x631)
```

**Pull request merged**
