### PR TITLE
Neptune nINJ, nATOM, nUSDT

### PR DESCRIPTION
**Pull request by 1biest**
Neptune finance protocol receipt tokens.
https://nept.finance/

### CODE REVIEW

**Comment by HeesungB** [comment]
@1biest Hello. Could you resize token image?
```
Reduce image size to 512x512 or smaller (expected: 512x512, actual: 590x590)
```

**Comment by 1biest** [comment]
@HeesungB Resized the images, also added an additional token.

**Comment by HeesungB** [comment]
@1biest Can you match the image name to the imageUrl?
You should also do the same with the upper and lower case letters.
```
"imageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-contract-registry/main/images/injective/natom.png",
...
images/injective/nATOM.png
```

**Comment by 1biest** [comment]
@HeesungB Corrected the incorrect file names.

**Pull request merged**
