### PR TITLE
add terraport token

### PR DESCRIPTION
**Pull request by Man12C**
add terraport token on terra classic chain

### CODE REVIEW

**Comment by HeesungB** [comment]
@Man12C Could you change image url path?
I think the path below is correct
```
https://raw.githubusercontent.com/chainapsis/keplr-contract-registry/main/images/columbus/terraport.png
```

**Comment by Man12C** [comment]
> @Man12C Could you change image url path? I think the path below is correct
> 
> ```
> https://raw.githubusercontent.com/chainapsis/keplr-contract-registry/main/images/columbus/terraport.png
> ```

Changed as requested, thank you!

**Comment by HeesungB** [comment]
@Man12C Could you rename image, url as symbol name?

**Comment by Man12C** [comment]
> @Man12C Could you rename image, url as symbol name?

Done

**Comment by HeesungB** [comment]
@Man12C Can I ask why did you remove json file?

**Comment by Man12C** [comment]
Can you merge it? 

> @Man12C Can I ask why did you remove json file?

**Comment by HeesungB** [comment]
@Man12C Could you resize image?
```
Reduce image size to 512x512 or smaller (expected: 512x512, actual: 630x640)
```

**Comment by Man12C** [comment]
> @Man12C Could you resize image?
> 
> ```
> Reduce image size to 512x512 or smaller (expected: 512x512, actual: 630x640)
> ```

Done

**Comment by Man12C** [comment]
Can you merge it?

**Pull request merged**
